language: java
install: true

jdk:
  - openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - openssl aes-256-cbc -K $encrypted_6afd0fc9428e_key -iv $encrypted_6afd0fc9428e_iv -in .travis/secring.gpg.enc -out secring.gpg -d
  
script: 
  - ./gradlew

deploy:
  provider: script 
  script: bash .travis/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    