language: java
install: true

jdk:
  - openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
  
script: 
  - ./gradlew
  
deploy:
  provider: script 
  script: "./gradlew bintrayUpload"
  skip_cleanup: true
  on:
    tags: true
    